# Generated by Django 5.2.13 on 2026-04-23 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_privacy_acceptance_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='temp_password',
            field=models.CharField(blank=True, help_text='Almacena la contraseña temporalmente hasta el envío del primer correo.', max_length=128, null=True),
        ),
    ]
